[package]
name = "megastore-search"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ordered-float = { version = "4.2.0", features = ["serde"] }

petgraph = "0.6"
